### ISSUE TITLE
Alchitry 1.1.2 cannot build

### ISSUE THREAD

**Issue by kurniawano** [alchitry/Alchitry-Labs#21] opened 2019-08-19 04:04 UTC
Hi,
I just updated to Alchitry Lab 1.1.2 and it fails to build on Alchitry Cu using IO Element Demo base project. I am using Windows 10. It gives the following error:

`Error : can not print out log file stdout.log`

I tried to upload the verilog and constrain files to Icecube2 and use Alchitry loader, and it works fine. So it seems it is not an issue on IceCube2 software.

Output log:

```
C:\Program Files\Alchitry\Alchitry Labs>C:\lscc\iCEcube2.2017.08\sbt_backend\bin\win32\opt\synpwrap\synpwrap.exe -prj "C:\Users\Documents\testbase\work\alchitry_syn.prj" -log "C:\Users\Documents\testbase\work\icelog.log" 
Error : can not print out log file stdout.log
Copyright (C) 1992-2014 Lattice Semiconductor Corporation. All rights reserved.
Error of dumping file C:\Users\Documents\testbase\work\icelog.log, 'stdout.log' is instead. 
Synthesis exit by 2.

C:\Program Files\Alchitry\Alchitry Labs>C:\lscc\iCEcube2.2017.08\Aldec\Active-HDL\BIN\tclsh85.exe "C:\Users\Documents\testbase\work\iCEcube2_flow.tcl" 

Run edifparser ...
{C:\lscc\iCEcube2.2017.08\sbt_backend/bin/win32/opt/edifparser} {C:\lscc\iCEcube2.2017.08\sbt_backend/devices\ICE40P08.dev} {C:/Users/Documents/testbase/work/alchitry_imp/cu_top_0.edf} {C:/Users/Documents/testbase/work/alchitry_imp/sbt/netlist}  -p"CB132"  {-y} {"C:/Users/Documents/testbase/work/constraint/merged_constraint.pcf "} --devicename  iCE40HX8K
Lattice Semiconductor Corporation  Edif Parser
Release:        2017.08.27940
Build Date:     Sep 11 2017 16:51:25

Parsing edif file: C:/Users/Documents/testbase/work/alchitry_imp/cu_top_0.edf...
Error: ParseEDIF C:/Users/Documents/testbase/work/alchitry_imp/cu_top_0.edf failed
Kparser Unable to open C:/Users/Documents/testbase/work/alchitry_imp/cu_top_0.edf
child process exited abnormally
edifparser failed:CHILDSTATUS 9856 1

Bin file (C:\Users\Documents\testbase\work\alchitry_imp\sbt\outputs\bitmap\cu_top_0_bitmap.bin) could not be found! The build probably failed.
```

**Comment by alchitry** [comment] 2021-06-09 17:04
Should be fixed in 1.2.6 or newer. This was caused by the new version of iCEcube2 removing the tcl script exectable.

**Closed as completed by alchitry** 2021-06-09 17:04 UTC
